schedule:
  - day: Monday
    open: "9:00 AM"
    close: "5:00 PM"

  - day: Tuesday
    open: "9:00 AM"
    close: "5:00 PM"

  - day: Wednesday
    open: "9:00 AM"
    close: "5:00 PM"

  - day: Thursday
    open: "9:00 AM"
    close: "5:00 PM"

  - day: Friday
    open: "9:00 AM"
    close: "5:00 PM"

display:
  off_hours_message: "Currently closed. Our business hours are Monday-Friday, 9 AM - 5 PM."
  schedule_header: Operating Hours
  schedule_time_format: "{open} - {close}"  # Format for displaying time ranges

remote:
  enabled: false  # Set to true to enable remote config
  url: ""  # GitLab Gist URL (e.g., https://gist.githubusercontent.com/user/gist_id)
  update_interval: 3600  # Update interval in seconds (default: 1 hour)
